name: libroo
version: 1.0.0+1
publish_to: 'none'
description: "A new Flutter project."
environment:
  sdk: ^3.7.2

dependencies:
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  get: ^4.7.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/image/
    - assets/image/intro-1.webp
    - assets/image/intro-2.webp
    - assets/image/intro-3.webp
    - assets/image/intro-4.webp
    - assets/image/intro-5.webp

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/libroo-icon.png"
