name: libroo
version: 1.0.0+1
publish_to: 'none'
description: "A new Flutter project."
environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/libroo-icon.png"
